# Generated by Django 3.1.3 on 2021-04-24 13:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('receive_newsletter', models.BooleanField(default=False)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('about_me', models.TextField(blank=True, max_length=500, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=900, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=9999999)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('who_can_edite', models.ManyToManyField(blank=True, related_name='who_can_edite_style', to=settings.AUTH_USER_MODEL)),
                ('who_can_see', models.ManyToManyField(blank=True, related_name='who_can_see_style', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('styles', models.CharField(blank=True, max_length=9999999)),
                ('postType', models.CharField(blank=True, max_length=50)),
                ('pre_build_style', models.ManyToManyField(blank=True, related_name='styles', to='api.Style')),
                ('who_can_edite', models.ManyToManyField(blank=True, related_name='who_can_edite_post', to=settings.AUTH_USER_MODEL)),
                ('who_can_see', models.ManyToManyField(blank=True, related_name='who_can_see_post', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('the_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='api.post')),
                ('who_can_edite', models.ManyToManyField(blank=True, related_name='who_can_edite_comment', to=settings.AUTH_USER_MODEL)),
                ('who_can_see', models.ManyToManyField(blank=True, related_name='who_can_see_comment', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.component',),
        ),
    ]
