# Generated by Django 3.1.3 on 2021-04-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='the_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='api.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='who_can_edite',
            field=models.ManyToManyField(blank=True, related_name='who_can_edite_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='who_can_see',
            field=models.ManyToManyField(blank=True, related_name='who_can_see_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.component')),
                ('who_can_edite', models.ManyToManyField(blank=True, related_name='who_can_edite_style', to=settings.AUTH_USER_MODEL)),
                ('who_can_see', models.ManyToManyField(blank=True, related_name='who_can_see_style', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.component',),
        ),
        migrations.AlterField(
            model_name='post',
            name='preBuildStyle',
            field=models.ManyToManyField(blank=True, related_name='styles', to='api.Style'),
        ),
    ]
